### ISSUE TITLE
Can't scroll down the page

### ISSUE THREAD

**Issue by IndraTensei** [hyperstown/pure-snow.js#6]
This prolly can be a silly question, But after putting this in my page I can't scroll down the page anymore.
Please guide me as I am new into programming 😆

**Comment by skippyr** [comment]
Hello, @IndraTensei. It seems that this is caused by a rule in the CSS that is there to improve performance. Try to remove the line `overflow-y: hidden;` that is affecting the `body` element from the `style.css` file.

https://github.com/hyperstown/pure-snow.js/blob/b3bcd4b190887779c4d3c6bc1de022c56d05768e/style.css#L1-L9
